package entrenamientogit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ariel
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setTitle("Menu Principal");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegistroUsuarios = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        RegistrarTema = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        Salir = new javax.swing.JButton();
        LBFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegistroUsuarios.setBackground(new java.awt.Color(0, 51, 102));
        RegistroUsuarios.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        RegistroUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        RegistroUsuarios.setText("Registrar Usuarios");
        RegistroUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(RegistroUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 160, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProgramaCharla/logo.scale-100.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        RegistrarTema.setBackground(new java.awt.Color(0, 51, 102));
        RegistrarTema.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        RegistrarTema.setForeground(new java.awt.Color(255, 255, 255));
        RegistrarTema.setText("Registrar Tema");
        RegistrarTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarTemaActionPerformed(evt);
            }
        });
        getContentPane().add(RegistrarTema, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 160, -1));

        jToggleButton2.setBackground(new java.awt.Color(0, 51, 102));
        jToggleButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jToggleButton2.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton2.setText("Lista De Inscritos");
        getContentPane().add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 160, -1));

        Salir.setBackground(new java.awt.Color(153, 0, 51));
        Salir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        LBFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProgramaCharla/fondo-de-tecnologia-azul_23-2147513140.jpg"))); // NOI18N
        getContentPane().add(LBFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_SalirActionPerformed

    private void RegistroUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroUsuariosActionPerformed
       VentanaRegistroU v2 = new VentanaRegistroU(this, true);
       v2.setVisible(true);
    }//GEN-LAST:event_RegistroUsuariosActionPerformed

    private void RegistrarTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarTemaActionPerformed
      VentanaRegistroT v3 = new VentanaRegistroT(this, true);
      v3.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrarTemaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBFondo;
    private javax.swing.JToggleButton RegistrarTema;
    private javax.swing.JToggleButton RegistroUsuarios;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
